#!/usr/bin/env bash
# ipabuild.sh — Build the iOS .app from the generated Luna.xcodeproj,
#               strip Swift symbols, stage Payload, and zip into an .ipa.
#
# Input:  ./Luna.xcodeproj (generated by XcodeGen from project.yml)
#         ./LunaAnime/.../Info.plist (target's Info.plist)
# Output: ./build/Luna.ipa (the actual IPA, which CI renames to LunaRyu.ipa)
#
# All code-signing flags are stripped so this produces an unsigned binary
# that SideStore can re-sign locally against the user's Apple ID.

set -euo pipefail

cd "$(dirname "$0")"

if [ ! -d "Luna.xcodeproj" ]; then
  echo "::error::Luna.xcodeproj not found. Run 'xcodegen generate --spec project.yml' first."
  exit 1
fi

rm -rf build
mkdir -p build

echo "==> Archive (Release, generic/device)"
xcodebuild \
  -project Luna.xcodeproj \
  -scheme Luna \
  -configuration Release \
  -destination "generic/platform=iOS" \
  -archivePath build/Luna.xcarchive \
  -derivedDataPath build/derivedData \
  ONLY_ACTIVE_ARCH=NO \
  ARCHS="arm64" \
  MARKETING_VERSION="1.1.0" \
  CURRENT_PROJECT_VERSION="2" \
  CODE_SIGNING_REQUIRED=NO \
  CODE_SIGN_IDENTITY="" \
  CODE_SIGNING_ALLOWED=NO \
  PROVISIONING_PROFILE_SPECIFIER="" \
  DEVELOPMENT_TEAM="" \
  archive | tee build/xcodebuild-archive.log | (xcbeautify 2>/dev/null || grep -E '^(\\*\\* BUILD|error:|warning: |note: )' || cat)

# Find the actual .app inside the archive
APP_PATH="$(find build/Luna.xcarchive/Products/Applications -maxdepth 1 -name '*.app' | head -1 || true)"
if [ -z "$APP_PATH" ]; then
  echo "::error::No .app found in build/Luna.xcarchive/Products/Applications"
  exit 1
fi
echo "==> Built app: $APP_PATH"
ls -la "$APP_PATH"

echo "==> Strip Swift interface/doc artifacts (defensive; usually none)"
find "$APP_PATH" \( -name '*.swiftinterface' -o -name '*.swiftdoc' \) -delete 2>/dev/null || true

echo "==> Stage Payload/"
rm -rf build/Payload
mkdir -p build/Payload
cp -R "$APP_PATH" build/Payload/

echo "==> Zip to build/Luna.ipa"
cd build
rm -f Luna.ipa
zip -r -y -q Luna.ipa Payload/
cd ..

echo
echo "==> Final artifact:"
ls -la build/Luna.ipa
file  build/Luna.ipa
du -h  build/Luna.ipa
